---
- name: Ensure mounted folder exists
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: directory
    recurse: true
    mode: "0775"
    owner: "{{ lxc_mount_user_name }}"
    group: "{{ lxc_mount_user_group }}"
  with_items: "{{ lxc_mount_mounts }}"

- name: Update lxc config
  include_tasks: update-conf.yml

- name: Add line to subuid file
  ansible.builtin.lineinfile:
    path: /etc/subuid
    line: root:{{ lxc_mount_user_uid }}:1
    regexp: ^root:{{ lxc_mount_user_uid }}
  notify:
    - Restart lxc
    - Start lxc

- name: Add line to subgid file
  ansible.builtin.lineinfile:
    path: /etc/subgid
    line: root:{{ lxc_mount_user_gid }}:1
    regexp: ^root:{{ lxc_mount_user_gid }}
  notify:
    - Restart lxc
    - Start lxc
