---
- name: Ensure mounted folder exists
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: directory
    recurse: true
    mode: "0775"
    owner: "{{ lxc_mount_user_name }}"
    group: "{{ lxc_mount_user_group }}"
  with_items: "{{ lxc_mount_mounts }}"

- name: Add mounts to lxc config
  ansible.builtin.blockinfile:
    block: |
      {% for mount in lxc_mount_mounts %}
      mp{{ loop.index - 1 }}: {{ mount.src }},mp={{ mount.dest }}
      {% endfor %}
    path: /etc/pve/lxc/{{ lxc_mount_lxc_id }}.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK mounts"
  notify: Restart lxc

- name: Add idmap to lxc config
  ansible.builtin.blockinfile:
    block: |
      lxc.idmap: u 0 100000 {{ lxc_mount_user_uid }}
      lxc.idmap: u {{ lxc_mount_user_uid }} {{ lxc_mount_user_uid }} 1
      lxc.idmap: u {{ lxc_mount_user_uid + 1 }} {{ lxc_mount_user_uid + 100001 }} {{ 165536 - lxc_mount_user_uid - 100001 }}
      lxc.idmap: g 0 100000 {{ lxc_mount_user_gid }}
      lxc.idmap: g {{ lxc_mount_user_gid }} {{ lxc_mount_user_gid }} 1
      lxc.idmap: g {{ lxc_mount_user_gid + 1 }} {{ lxc_mount_user_gid + 100001 }} {{ 165536 - lxc_mount_user_gid - 100001 }}
    path: /etc/pve/lxc/{{ lxc_mount_lxc_id }}.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK idmap"
  notify: Restart lxc

- name: Add line to subuid file
  ansible.builtin.lineinfile:
    path: /etc/subuid
    line: root:{{ lxc_mount_user_uid }}:1
    regexp: ^root:{{ lxc_mount_user_uid }}
  notify: Restart lxc

- name: Add line to subgid file
  ansible.builtin.lineinfile:
    path: /etc/subgid
    line: root:{{ lxc_mount_user_gid }}:1
    regexp: ^root:{{ lxc_mount_user_gid }}
  notify: Restart lxc
