---
- name: Ensure mounted folders exist
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: directory
    mode: "{{ lxc_mount_permissions }}"
    owner: "{{ lxc_mount_user_name }}"
    group: "{{ lxc_mount_user_group }}"
  loop: "{{ lxc_mount_mounts }}"
